import React, { useState, useMemo } from 'react';
import Layout from '@theme/Layout';
import clsx from 'clsx';
import styles from './models.module.css';
import ModelCard from '../components/ModelCard';

// Import the generated models data
// This file will be generated by scripts/fetch-models.js during build
import modelsData from '../data/models.json';

interface Model {
  id: string;
  name: string;
  description: string;
  version: string;
  parameters: string | null;
  platforms: string[];
  isExperimental: boolean;
  tags: string[];
  isVision: boolean;
  huggingfaceUrl: string | null;
}

type FilterType = 'cuda' | 'metal' | 'desktop-macos' | 'vision' | 'experimental';

export default function Models(): JSX.Element {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeFilters, setActiveFilters] = useState<Set<FilterType>>(new Set());

  const models = modelsData as Model[];

  // Toggle filter on/off
  const toggleFilter = (filter: FilterType) => {
    setActiveFilters(prev => {
      const newFilters = new Set(prev);
      if (newFilters.has(filter)) {
        newFilters.delete(filter);
      } else {
        newFilters.add(filter);
      }
      return newFilters;
    });
  };

  // Filter and search models
  const filteredModels = useMemo(() => {
    return models.filter(model => {
      // Search filter
      const matchesSearch =
        searchQuery === '' ||
        model.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        model.description.toLowerCase().includes(searchQuery.toLowerCase());

      if (!matchesSearch) return false;

      // If no filters active, show all
      if (activeFilters.size === 0) return true;

      // Platform filters (OR logic)
      const platformFilters = ['cuda', 'metal', 'desktop-macos'] as const;
      const activePlatformFilters = platformFilters.filter(f => activeFilters.has(f));

      const matchesPlatform =
        activePlatformFilters.length === 0 ||
        activePlatformFilters.some(filter => model.platforms.includes(filter));

      // Vision filter
      const matchesVision =
        !activeFilters.has('vision') || model.isVision;

      // Experimental filter
      const matchesExperimental =
        !activeFilters.has('experimental') || model.isExperimental;

      return matchesPlatform && matchesVision && matchesExperimental;
    });
  }, [models, searchQuery, activeFilters]);

  return (
    <Layout
      title="Supported Models"
      description="Browse all models supported by Pie"
    >
      <main className={styles.modelsPage}>
        <div className="container">
          <header className={styles.pageHeader}>
            <h1>Supported Models</h1>
            <p className={styles.pageDescription}>
              Browse and search through all models supported by Pie. Use the filters below to find models by platform or capability.
            </p>
          </header>

          {/* Search Bar */}
          <div className={styles.searchSection}>
            <input
              type="text"
              className={styles.searchInput}
              placeholder="Search models..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              aria-label="Search models"
            />
          </div>

          {/* Filters */}
          <div className={styles.filtersSection}>
            <div className={styles.filterLabel}>Filters:</div>
            <div className={styles.filterButtons}>
              <button
                className={clsx(styles.filterButton, {
                  [styles.filterButtonActive]: activeFilters.has('cuda'),
                })}
                onClick={() => toggleFilter('cuda')}
              >
                CUDA
              </button>
              <button
                className={clsx(styles.filterButton, {
                  [styles.filterButtonActive]: activeFilters.has('metal'),
                })}
                onClick={() => toggleFilter('metal')}
              >
                Metal
              </button>
              <button
                className={clsx(styles.filterButton, {
                  [styles.filterButtonActive]: activeFilters.has('desktop-macos'),
                })}
                onClick={() => toggleFilter('desktop-macos')}
              >
                Desktop (Mac)
              </button>
              <button
                className={clsx(styles.filterButton, {
                  [styles.filterButtonActive]: activeFilters.has('vision'),
                })}
                onClick={() => toggleFilter('vision')}
              >
                Vision
              </button>
              <button
                className={clsx(styles.filterButton, {
                  [styles.filterButtonActive]: activeFilters.has('experimental'),
                })}
                onClick={() => toggleFilter('experimental')}
              >
                Experimental
              </button>
            </div>
          </div>

          {/* Results Count */}
          <div className={styles.resultsCount}>
            {filteredModels.length} {filteredModels.length === 1 ? 'model' : 'models'}
          </div>

          {/* Models Grid */}
          <div className={styles.modelsGrid}>
            {filteredModels.length > 0 ? (
              filteredModels.map(model => (
                <ModelCard key={model.id} model={model} />
              ))
            ) : (
              <div className={styles.noResults}>
                <p>No models found matching your search criteria.</p>
                <button
                  className={styles.clearButton}
                  onClick={() => {
                    setSearchQuery('');
                    setActiveFilters(new Set());
                  }}
                >
                  Clear all filters
                </button>
              </div>
            )}
          </div>
        </div>
      </main>
    </Layout>
  );
}
