package inferlib:cacheback;

interface cacheback {
    resource cache-table {
        constructor(
            leader-capacity: u32,
            follower-capacity: u32,
            leader-len: u32,
            follower-len: u32,
        );
        update-cache: func(token-ids: list<u32>);
        get-draft-tokens: func(leader: list<u32>) -> list<list<u32>>;
        clear: func();
    }
}
