# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class ConstrainedSampler:
    
    def __init__(self, vocab_ids: List[int], vocab_bytes: List[bytes], special_token_ids: List[int], special_token_bytes: List[bytes], split_regex: str, grammar: str, eos_token_id: int, escape_non_printable: bool) -> None:
        raise NotImplementedError

    def sample(self, token_ids: List[int], probs: List[float]) -> int:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class TokenMask:
    
    def first_bit_set(self) -> Optional[int]:
        raise NotImplementedError
    def is_allowed(self, token_id: int) -> bool:
        raise NotImplementedError
    def is_empty(self) -> bool:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class GrammarMatcher:
    
    def compute_mask(self) -> Optional[TokenMask]:
        raise NotImplementedError
    def consume_token(self, token_id: int) -> None:
        raise NotImplementedError
    def __init__(self, vocab_ids: List[int], vocab_bytes: List[bytes], special_token_ids: List[int], special_token_bytes: List[bytes], split_regex: str, grammar: str, eos_token_id: int, escape_non_printable: bool) -> None:
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



