"""
schema_bindings - Thin Python wrapper over inferlib-schema WIT bindings.

Generated by sdk/rust/inferlib-rust-to-bindings.
"""

from wit_world.imports import json_schema as _json_schema

SchemaValidator = _json_schema.SchemaValidator

__all__ = [
    "SchemaValidator",
]
