//! Library component that shadows the Pie runtime API.
//!
//! This component exports the Pie runtime API (`inferlet:core/runtime`) but does not
//! import it from the engine. Instead, it provides shadow implementations that return
//! default values for each function call.
//!
//! Used for testing that components can fully replace the runtime API without depending
//! on the engine's implementation.

// Import the bindings generated by wit-bindgen
wit_bindgen::generate!({
    world: "runtime-shadow",
    path: "wit",
    with: {
        "wasi:io/poll@0.2.4": wasi::io::poll,
        "inferlet:core/common": generate,
        "inferlet:core/runtime": generate,
    },
});

use exports::inferlet::core::common;
use exports::inferlet::core::runtime;

struct RuntimeShadow;
struct ShadowDebugQueryResult;

impl common::GuestDebugQueryResult for ShadowDebugQueryResult {
    fn pollable(&self) -> wasi::io::poll::Pollable {
        panic!("Shadow implementation: pollable not supported")
    }

    fn get(&self) -> Option<String> {
        Some("shadow-result".to_string())
    }
}

// Implement the exported common interface with minimal/shadow implementations
impl common::Guest for RuntimeShadow {
    type Blob = ShadowBlob;
    type BlobResult = ShadowBlobResult;
    type Model = ShadowModel;
    type Queue = ShadowQueue;
    type SynchronizationResult = ShadowSynchronizationResult;
    type DebugQueryResult = ShadowDebugQueryResult;

    fn allocate_resources(
        _queue: common::QueueBorrow<'_>,
        _resource_type: u32,
        _count: u32,
    ) -> Vec<u32> {
        vec![]
    }

    fn deallocate_resources(_queue: common::QueueBorrow<'_>, _resource_type: u32, _ptrs: Vec<u32>) {
        // No-op
    }

    fn get_all_exported_resources(
        _queue: common::QueueBorrow<'_>,
        _resource_type: u32,
    ) -> Vec<(String, u32)> {
        vec![]
    }

    fn release_exported_resources(
        _queue: common::QueueBorrow<'_>,
        _resource_type: u32,
        _name: String,
    ) {
        // No-op
    }

    fn export_resources(
        _queue: common::QueueBorrow<'_>,
        _resource_type: u32,
        _ptrs: Vec<u32>,
        _name: String,
    ) {
        // No-op
    }

    fn import_resources(
        _queue: common::QueueBorrow<'_>,
        _resource_type: u32,
        _name: String,
    ) -> Vec<u32> {
        vec![]
    }
}

// Minimal resource implementations for common interface
struct ShadowBlob(Vec<u8>);
struct ShadowBlobResult;
struct ShadowModel;
struct ShadowQueue;
struct ShadowSynchronizationResult;

impl common::GuestBlob for ShadowBlob {
    fn new(init: Vec<u8>) -> Self {
        ShadowBlob(init)
    }

    fn read(&self, offset: u64, n: u64) -> Vec<u8> {
        let start = offset as usize;
        let end = std::cmp::min(start + n as usize, self.0.len());
        self.0.get(start..end).unwrap_or(&[]).to_vec()
    }

    fn size(&self) -> u64 {
        self.0.len() as u64
    }
}

impl common::GuestBlobResult for ShadowBlobResult {
    fn pollable(&self) -> wasi::io::poll::Pollable {
        panic!("Shadow implementation: pollable not supported")
    }

    fn get(&self) -> Option<common::Blob> {
        None
    }
}

impl common::GuestModel for ShadowModel {
    fn get_name(&self) -> String {
        "shadow-model".to_string()
    }

    fn get_traits(&self) -> Vec<String> {
        vec![]
    }

    fn get_description(&self) -> String {
        "Shadow model".to_string()
    }

    fn get_prompt_template(&self) -> String {
        String::new()
    }

    fn get_stop_tokens(&self) -> Vec<String> {
        vec![]
    }

    fn get_service_id(&self) -> u32 {
        0
    }

    fn get_kv_page_size(&self) -> u32 {
        4096
    }

    fn create_queue(&self) -> common::Queue {
        common::Queue::new(ShadowQueue)
    }
}

impl common::GuestQueue for ShadowQueue {
    fn get_service_id(&self) -> u32 {
        0
    }

    fn synchronize(&self) -> common::SynchronizationResult {
        common::SynchronizationResult::new(ShadowSynchronizationResult)
    }

    fn set_priority(&self, _priority: common::Priority) {
        // No-op
    }

    fn debug_query(&self, _query: String) -> common::DebugQueryResult {
        common::DebugQueryResult::new(ShadowDebugQueryResult)
    }
}

impl common::GuestSynchronizationResult for ShadowSynchronizationResult {
    fn pollable(&self) -> wasi::io::poll::Pollable {
        panic!("Shadow implementation: pollable not supported")
    }

    fn get(&self) -> Option<bool> {
        Some(true)
    }
}

// Implement the exported runtime interface with shadow/default values
impl runtime::Guest for RuntimeShadow {
    /// Return a shadow version string.
    fn get_version() -> String {
        "shadow-version".to_string()
    }

    /// Return a default instance ID.
    fn get_instance_id() -> String {
        "shadow-instance".to_string()
    }

    /// Return an empty arguments list.
    fn get_arguments() -> Vec<String> {
        vec![]
    }

    /// No-op implementation for setting return value.
    fn set_return(_value: String) {
        // Shadow implementation does nothing
    }

    /// Return None for any model query.
    fn get_model(_name: String) -> Option<common::Model> {
        None
    }

    /// Return an empty models list.
    fn get_all_models() -> Vec<String> {
        vec![]
    }

    /// Return an empty models list regardless of traits.
    fn get_all_models_with_traits(_traits: Vec<String>) -> Vec<String> {
        vec![]
    }

    /// Return a default debug query result.
    fn debug_query(_query: String) -> common::DebugQueryResult {
        common::DebugQueryResult::new(ShadowDebugQueryResult)
    }
}

// Export the implementation
export!(RuntimeShadow);
