# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class ToolCall:
    name: str
    arguments: str

class ChatFormatter:
    
    def add_assistant(self, content: str) -> None:
        raise NotImplementedError
    def add_assistant_response(self, content: str, reasoning: Optional[str], tool_calls: Optional[List[ToolCall]]) -> None:
        raise NotImplementedError
    def add_system(self, content: str) -> None:
        raise NotImplementedError
    def add_tool(self, content: str) -> None:
        raise NotImplementedError
    def add_user(self, content: str) -> None:
        raise NotImplementedError
    def clear(self) -> None:
        raise NotImplementedError
    def has_messages(self) -> bool:
        raise NotImplementedError
    def __init__(self, template: str) -> None:
        raise NotImplementedError

    def render(self, add_generation_prompt: bool, begin_of_sequence: bool) -> str:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



