# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import models
from ..imports import queues
from ..imports import poll


@dataclass
class SamplerConfig_Greedy:
    pass


@dataclass
class SamplerConfig_Multinomial:
    value: float


@dataclass
class SamplerConfig_TopP:
    value: Tuple[float, float]


@dataclass
class SamplerConfig_TopK:
    value: Tuple[float, int]


@dataclass
class SamplerConfig_MinP:
    value: Tuple[float, float]


@dataclass
class SamplerConfig_TopKTopP:
    value: Tuple[float, int, float]


SamplerConfig = Union[SamplerConfig_Greedy, SamplerConfig_Multinomial, SamplerConfig_TopP, SamplerConfig_TopK, SamplerConfig_MinP, SamplerConfig_TopKTopP]


class DecodeStepFuture:
    
    def get(self) -> Optional[int]:
        raise NotImplementedError
    def pollable(self) -> poll.Pollable:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class FlushFuture:
    
    def is_ready(self) -> bool:
        raise NotImplementedError
    def pollable(self) -> poll.Pollable:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class StopConfig:
    max_tokens: int
    eos_sequences: List[List[int]]

class GenerateFuture:
    
    def get(self) -> Optional[str]:
        raise NotImplementedError
    def pollable(self) -> poll.Pollable:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Context:
    
    def decode_step(self, sampler: SamplerConfig) -> int:
        raise NotImplementedError
    def decode_step_async(self, sampler: SamplerConfig) -> DecodeStepFuture:
        raise NotImplementedError
    def decode_step_dist(self, temperature: float, top_k: Optional[int]) -> queues.Distribution:
        raise NotImplementedError
    def detokenize(self, token_ids: List[int]) -> str:
        raise NotImplementedError
    def drop_masked_kv_pages(self) -> None:
        raise NotImplementedError
    def fill(self, text: str) -> None:
        raise NotImplementedError
    def fill_assistant(self, text: str) -> None:
        raise NotImplementedError
    def fill_system(self, text: str) -> None:
        raise NotImplementedError
    def fill_token(self, new_token_id: int) -> None:
        raise NotImplementedError
    def fill_tokens(self, new_token_ids: List[int]) -> None:
        raise NotImplementedError
    def fill_user(self, text: str) -> None:
        raise NotImplementedError
    def fill_user_only(self, text: str) -> None:
        raise NotImplementedError
    def flush(self) -> None:
        raise NotImplementedError
    def flush_async(self) -> Optional[FlushFuture]:
        raise NotImplementedError
    def flush_chat_messages(self, add_generation_prompt: bool) -> None:
        raise NotImplementedError
    def fork(self) -> Self:
        raise NotImplementedError
    @classmethod
    def from_imported_state(cls, wit_model: models.Model, kv_page_ptrs: List[int], prefix_tokens: List[int], kv_page_last_len: int) -> Self:
        raise NotImplementedError
    def generate(self, sampler: SamplerConfig, stop_config: StopConfig) -> str:
        raise NotImplementedError
    def generate_async(self, sampler: SamplerConfig, stop_config: StopConfig) -> GenerateFuture:
        raise NotImplementedError
    def generate_with_beam(self, stop_config: StopConfig, beam_size: int) -> str:
        raise NotImplementedError
    def get_kv_page_last_len(self) -> int:
        raise NotImplementedError
    def get_kv_page_ptrs(self) -> List[int]:
        raise NotImplementedError
    def get_text(self) -> str:
        raise NotImplementedError
    def get_token_ids(self) -> List[int]:
        raise NotImplementedError
    def mask_token(self, index: int, mask: bool) -> None:
        raise NotImplementedError
    def mask_token_range(self, start: int, end: int, mask: bool) -> None:
        raise NotImplementedError
    def mask_tokens(self, indices: List[int], mask: bool) -> None:
        raise NotImplementedError
    def __init__(self, wit_model: models.Model) -> None:
        raise NotImplementedError

    def remove_adapter(self) -> None:
        raise NotImplementedError
    def set_adapter(self, adapter_ptr: int) -> None:
        raise NotImplementedError
    def set_adapter_random_seed(self, seed: int) -> None:
        raise NotImplementedError
    def verify_draft(self, draft_tokens: List[int], draft_pos_ids: List[int]) -> List[int]:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



