# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def store_delete(key: str) -> None:
    raise NotImplementedError
def store_exists(key: str) -> bool:
    raise NotImplementedError
def store_get(key: str) -> Optional[str]:
    raise NotImplementedError
def store_list_keys() -> List[str]:
    raise NotImplementedError
def store_set(key: str, value: str) -> None:
    raise NotImplementedError
