# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def broadcast(topic: str, message: str) -> None:
    raise NotImplementedError
def receive() -> str:
    raise NotImplementedError
def receive_blob() -> bytes:
    raise NotImplementedError
def send(message: str) -> None:
    raise NotImplementedError
def send_blob(data: bytes) -> None:
    raise NotImplementedError
def subscribe(topic: str) -> str:
    raise NotImplementedError
