# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Tokenizer:
    
    def detokenize(self, tokens: List[int]) -> str:
        raise NotImplementedError
    def get_special_tokens(self) -> Tuple[List[int], List[bytes]]:
        raise NotImplementedError
    def get_split_regex(self) -> str:
        raise NotImplementedError
    def get_vocabs(self) -> Tuple[List[int], List[bytes]]:
        raise NotImplementedError
    def tokenize(self, text: str) -> List[int]:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Model:
    
    def eos_tokens(self) -> List[List[int]]:
        raise NotImplementedError
    @classmethod
    def get_all_names(cls) -> List[str]:
        raise NotImplementedError
    @classmethod
    def get_auto(cls) -> Self:
        raise NotImplementedError
    @classmethod
    def get_by_name(cls, name: str) -> Optional[Self]:
        raise NotImplementedError
    def get_description(self) -> str:
        raise NotImplementedError
    def get_kv_page_size(self) -> int:
        raise NotImplementedError
    def get_name(self) -> str:
        raise NotImplementedError
    def get_prompt_template(self) -> str:
        raise NotImplementedError
    def get_service_id(self) -> int:
        raise NotImplementedError
    def get_tokenizer(self) -> Tokenizer:
        raise NotImplementedError
    def get_traits(self) -> List[str]:
        raise NotImplementedError
    def has_traits(self, required_traits: List[str]) -> bool:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



