# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class Distribution:
    ids: List[int]
    probs: List[float]

@dataclass
class ForwardPassResult:
    distributions: Optional[List[Distribution]]
    tokens: Optional[List[int]]

class ForwardPass:
    
    def attention_mask(self, mask: List[List[int]]) -> None:
        raise NotImplementedError
    def execute(self) -> ForwardPassResult:
        raise NotImplementedError
    def input_embed_ptrs(self, embed_ptrs: List[int], positions: List[int]) -> None:
        raise NotImplementedError
    def input_tokens(self, tokens: List[int], positions: List[int]) -> None:
        raise NotImplementedError
    def kv_cache(self, kv_page_ptrs: List[int], last_kv_page_len: int) -> None:
        raise NotImplementedError
    def output_distributions(self, indices: List[int], temperature: float, top_k: Optional[int]) -> None:
        raise NotImplementedError
    def output_embed_ptrs(self, embed_ptrs: List[int], indices: List[int]) -> None:
        raise NotImplementedError
    def output_tokens(self, indices: List[int], temperature: float) -> None:
        raise NotImplementedError
    def output_tokens_min_p(self, indices: List[int], temperature: float, min_p: float) -> None:
        raise NotImplementedError
    def output_tokens_top_k(self, indices: List[int], temperature: float, top_k: int) -> None:
        raise NotImplementedError
    def output_tokens_top_k_top_p(self, indices: List[int], temperature: float, top_k: int, top_p: float) -> None:
        raise NotImplementedError
    def output_tokens_top_p(self, indices: List[int], temperature: float, top_p: float) -> None:
        raise NotImplementedError
    def set_adapter(self, adapter_ptr: int) -> None:
        raise NotImplementedError
    def set_adapter_seed(self, seed: int) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class KvPage:
    
    def ptr(self) -> int:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Priority(Enum):
    LOW = 0
    NORMAL = 1
    HIGH = 2

class Queue:
    
    def allocate_adapter(self) -> int:
        raise NotImplementedError
    def allocate_embeds(self, count: int) -> List[int]:
        raise NotImplementedError
    def allocate_kv_pages(self, count: int) -> List[int]:
        raise NotImplementedError
    def calculate_embed_size(self, image_width: int, image_height: int) -> int:
        raise NotImplementedError
    def create_forward_pass(self) -> ForwardPass:
        raise NotImplementedError
    def deallocate_adapter(self, ptr: int) -> None:
        raise NotImplementedError
    def deallocate_embeds(self, ptrs: List[int]) -> None:
        raise NotImplementedError
    def deallocate_kv_pages(self, ptrs: List[int]) -> None:
        raise NotImplementedError
    def debug_query(self, query: str) -> str:
        raise NotImplementedError
    def download_adapter(self, adapter_ptr: int, name: str) -> None:
        raise NotImplementedError
    def embed_image(self, embed_ptrs: List[int], image_data: bytes, position_offset: int) -> None:
        raise NotImplementedError
    def export_adapter(self, ptr: int, name: str) -> None:
        raise NotImplementedError
    def export_embeds(self, ptrs: List[int], name: str) -> None:
        raise NotImplementedError
    def export_kv_pages(self, ptrs: List[int], name: str) -> None:
        raise NotImplementedError
    @classmethod
    def from_model_name(cls, model_name: str) -> Self:
        raise NotImplementedError
    def get_all_exported_adapters(self) -> List[str]:
        raise NotImplementedError
    def get_all_exported_embeds(self) -> List[Tuple[str, int]]:
        raise NotImplementedError
    def get_all_exported_kv_pages(self) -> List[Tuple[str, int]]:
        raise NotImplementedError
    def get_service_id(self) -> int:
        raise NotImplementedError
    def import_adapter(self, name: str) -> int:
        raise NotImplementedError
    def import_embeds(self, name: str) -> List[int]:
        raise NotImplementedError
    def import_kv_pages(self, name: str) -> List[int]:
        raise NotImplementedError
    def initialize_adapter(self, adapter_ptr: int, rank: int, alpha: float, population_size: int, mu_fraction: float, initial_sigma: float) -> None:
        raise NotImplementedError
    def release_exported_adapter(self, name: str) -> None:
        raise NotImplementedError
    def release_exported_embeds(self, name: str) -> None:
        raise NotImplementedError
    def release_exported_kv_pages(self, name: str) -> None:
        raise NotImplementedError
    def set_priority(self, priority: Priority) -> None:
        raise NotImplementedError
    def synchronize(self) -> bool:
        raise NotImplementedError
    def update_adapter(self, adapter_ptr: int, scores: List[float], seeds: List[int], max_sigma: float) -> None:
        raise NotImplementedError
    def upload_adapter(self, adapter_ptr: int, name: str, data: bytes) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class ResourceType(Enum):
    KV_PAGE = 0
    EMBED = 1
    ADAPTER = 2


