# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def debug_query(query: str) -> str:
    raise NotImplementedError
def get_all_models_with_traits(traits: List[str]) -> List[str]:
    raise NotImplementedError
def get_arguments() -> List[str]:
    raise NotImplementedError
def get_instance_id() -> str:
    raise NotImplementedError
def get_version() -> str:
    raise NotImplementedError
def set_return(value: str) -> None:
    raise NotImplementedError
