package inferlib:schema;

interface json-schema {
    resource schema-validator {
        constructor(schema-str: string);
        validate: func(json-str: string) -> result<string, string>;
    }

}
