"""
js_engine_bindings - Thin Python wrapper over inferlib-js-engine WIT bindings.

Generated by sdk/rust/inferlib-rust-to-bindings.
"""

from wit_world.imports import js_engine as _js_engine

execute = _js_engine.execute

__all__ = [
    "execute",
]
