def apply_rope_pos_ids_inplace(*args, **kwargs): ...
def apply_llama31_rope_pos_ids_inplace(*args, **kwargs): ...
def append_paged_kv_cache(*args, **kwargs): ...
def get_batch_indices_positions(*args, **kwargs): ...
def get_seq_lens(*args, **kwargs): ...
def BatchDecodeWithPagedKVCacheWrapper(*args, **kwargs): ...
def BatchPrefillWithPagedKVCacheWrapper(*args, **kwargs): ...
