[package]
name = "text-completion-inferlib3"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlib3-inference-bindings = { path = "../../rust/inferlib3/inference-bindings" }
inferlib-old-run-bindings = { path = "../../rust/inferlib-old/run-bindings" }
inferlib3-macros = { path = "../../rust/inferlib3-macros" }
