[package]
name = "text-completion-inferlib4"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlib4-inference-bindings = { path = "../../rust/inferlib4/inference-bindings" }
inferlib4-run-bindings = { path = "../../rust/inferlib4/run-bindings" }
inferlib4-macros = { path = "../../rust/inferlib4-macros" }
