interface adapter {

    use core.{queue, pointer, blob, blob-result};
    use forward.{forward-pass};

    set-adapter: func(
        pass: borrow<forward-pass>,
        adapter-ptr: pointer
    );

    download-adapter: func(
        queue: borrow<queue>,
        adapter-ptr: pointer,
        name: string
    ) -> blob-result;

    upload-adapter: func(
        queue: borrow<queue>,
        adapter-ptr: pointer,
        name: string,
        blob: blob
    );

}