package pie:inferlet;

world traits {
    import forward;
    import tokenize;
    import image;
    import adapter;
    import evolve;
}

world imports {
    include traits;
    import core;
}

world inferlet {
    include imports;
    export run;
}

world inferlet-server {
    include imports;
    export wasi:http/incoming-handler@0.2.4;
}