# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class DraftResult:
    tokens: List[int]
    positions: List[int]

class CacheTable:
    
    def clear(self) -> None:
        raise NotImplementedError
    def draft(self) -> DraftResult:
        raise NotImplementedError
    def __init__(self, leader_capacity: int, follower_capacity: int, leader_len: int, follower_len: int) -> None:
        raise NotImplementedError

    def update(self, context: List[int]) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



