interface system {

  resource channel {
    constructor();
    request: func(message: string) -> string;
    send: func(message: string);
    fetch: func() -> string;
  }

  get-version: func() -> string;
}
