"""
cacheback_bindings - Thin Python wrapper over inferlib-cacheback WIT bindings.

Generated by sdk/rust/inferlib-rust-to-bindings.
"""

from wit_world.imports import cacheback as _cacheback

CacheTable = _cacheback.CacheTable
DraftResult = _cacheback.DraftResult

__all__ = [
    "CacheTable",
    "DraftResult",
]
