"""
template_bindings - Thin Python wrapper over inferlib-template WIT bindings.

Generated by sdk/rust/inferlib-rust-to-bindings.
"""

from wit_world.imports import template_rendering as _template_rendering

TemplateRenderer = _template_rendering.TemplateRenderer

__all__ = [
    "TemplateRenderer",
]
