package inferlib:inference;

world inference-provider {
    import wasi:io/poll@0.2.0;

    export models;
    export queues;
    export runtime;
    export inference;
    export formatter;
    export messaging;
    export kvstore;
}
