// Import the bindings generated by wit-bindgen
wit_bindgen::generate!({
    world: "runtime-instrument",
    path: "wit",
    with: {
        "wasi:io/poll@0.2.4": wasi::io::poll,
        "inferlet:core/common": generate,
        "inferlet:core/runtime": generate,
    },
});

use exports::inferlet::core::runtime::Guest;

// Import the actual runtime implementation
use inferlet::core::common as imported_common;
use inferlet::core::runtime as imported_runtime;

struct RuntimeInstrument;

// Implement the exported runtime interface
impl Guest for RuntimeInstrument {
    /// Instrument the `get_version` method.
    fn get_version() -> String {
        let version = imported_runtime::get_version();
        format!("Instrumented: {}", version)
    }

    /// Pass through to the imported implementation
    fn get_instance_id() -> String {
        imported_runtime::get_instance_id()
    }

    /// Pass through to the imported implementation
    fn get_arguments() -> Vec<String> {
        imported_runtime::get_arguments()
    }

    /// Pass through to the imported implementation
    fn set_return(value: String) {
        imported_runtime::set_return(&value)
    }

    /// Pass through to the imported implementation
    fn get_model(name: String) -> Option<imported_common::Model> {
        imported_runtime::get_model(&name)
    }

    /// Pass through to the imported implementation
    fn get_all_models() -> Vec<String> {
        imported_runtime::get_all_models()
    }

    /// Pass through to the imported implementation
    fn get_all_models_with_traits(traits: Vec<String>) -> Vec<String> {
        imported_runtime::get_all_models_with_traits(&traits)
    }

    /// Pass through to the imported implementation
    fn debug_query(query: String) -> imported_common::DebugQueryResult {
        imported_runtime::debug_query(&query)
    }
}

// Export the implementation
export!(RuntimeInstrument);
