package spi:core;

interface inference {
  resource language-model {
    constructor(model-id:string);
    tokenize: func(text: string) -> list<u32>;
    detokenize: func(tokens: list<u32>) -> string;
    predict: func(tokens: list<u32>) -> u32;
  }
}

interface system {
    ask: func(question: string) -> string;
    tell: func(message: string);
}

interface run {
    run: func() -> result;
}


world imports {
    import inference;
    import system;
}