[workspace]
resolver = "2"
members = [
    "agent-codeact",
    "agent-react",
    "agent-swarm",
    "attention-sink",
    "best-of-n",
    "cacheback-decoding",
    "constrained-decoding",
    "graph-of-thought",
    "jacobi-decoding",
    "json-schema-validation",
    "knowledge-graph",
    "output-validation",
    "parallel-generation",
    "prefix-caching",
    "prefix-tree",
    "recursion-of-thought",
    "skeleton-of-thought",
    "template-generation",
    "text-completion-inferlib",
    "tree-of-thought",
    "watermarking",
    "windowed-attention",
]

[profile.release]
lto = true
