"""
inference_bindings - Thin Python wrapper over inferlib-inference WIT bindings.

Generated by sdk/rust/inferlib-rust-to-bindings.
"""

from wit_world.imports import poll as _poll
from wit_world.imports import formatter as _formatter
from wit_world.imports import inference as _inference
from wit_world.imports import kvstore as _kvstore
from wit_world.imports import messaging as _messaging
from wit_world.imports import models as _models
from wit_world.imports import queues as _queues
from wit_world.imports import runtime as _runtime

Pollable = _poll.Pollable
poll = _poll.poll

ChatFormatter = _formatter.ChatFormatter
ToolCall = _formatter.ToolCall

Context = _inference.Context
DecodeStepFuture = _inference.DecodeStepFuture
FlushFuture = _inference.FlushFuture
GenerateFuture = _inference.GenerateFuture
StopConfig = _inference.StopConfig
SamplerConfig = _inference.SamplerConfig
SamplerConfig_Greedy = _inference.SamplerConfig_Greedy
SamplerConfig_Multinomial = _inference.SamplerConfig_Multinomial
SamplerConfig_TopP = _inference.SamplerConfig_TopP
SamplerConfig_TopK = _inference.SamplerConfig_TopK
SamplerConfig_MinP = _inference.SamplerConfig_MinP
SamplerConfig_TopKTopP = _inference.SamplerConfig_TopKTopP

store_delete = _kvstore.store_delete
store_exists = _kvstore.store_exists
store_get = _kvstore.store_get
store_list_keys = _kvstore.store_list_keys
store_set = _kvstore.store_set

broadcast = _messaging.broadcast
receive = _messaging.receive
receive_blob = _messaging.receive_blob
send = _messaging.send
send_blob = _messaging.send_blob
subscribe = _messaging.subscribe

Model = _models.Model
Tokenizer = _models.Tokenizer

ForwardPass = _queues.ForwardPass
KvPage = _queues.KvPage
Queue = _queues.Queue
Distribution = _queues.Distribution
ForwardPassResult = _queues.ForwardPassResult
Priority = _queues.Priority
ResourceType = _queues.ResourceType

debug_query = _runtime.debug_query
get_all_models_with_traits = _runtime.get_all_models_with_traits
get_arguments = _runtime.get_arguments
get_instance_id = _runtime.get_instance_id
get_version = _runtime.get_version
set_return = _runtime.set_return

__all__ = [
    "Pollable",
    "poll",
    "ChatFormatter",
    "ToolCall",
    "Context",
    "DecodeStepFuture",
    "FlushFuture",
    "GenerateFuture",
    "StopConfig",
    "SamplerConfig",
    "SamplerConfig_Greedy",
    "SamplerConfig_Multinomial",
    "SamplerConfig_TopP",
    "SamplerConfig_TopK",
    "SamplerConfig_MinP",
    "SamplerConfig_TopKTopP",
    "store_delete",
    "store_exists",
    "store_get",
    "store_list_keys",
    "store_set",
    "broadcast",
    "receive",
    "receive_blob",
    "send",
    "send_blob",
    "subscribe",
    "Model",
    "Tokenizer",
    "ForwardPass",
    "KvPage",
    "Queue",
    "Distribution",
    "ForwardPassResult",
    "Priority",
    "ResourceType",
    "debug_query",
    "get_all_models_with_traits",
    "get_arguments",
    "get_instance_id",
    "get_version",
    "set_return",
]
