[workspace]
resolver = "2"
members = [
    "func-call-latency/inferlib-r2r-echo-callee",
    "func-call-latency/inferlib-r2r-echo-callee-bindings",
    "func-call-latency/inferlib-r2r-echo-caller",
    "func-call-latency/inferlib-r2h-host-echo-bindings",
    "func-call-latency/inferlib-r2h-echo-caller",
    "func-call-latency/inferlib-h2r-benchmark-bindings",
    "func-call-latency/inferlib-h2r-echo-caller",
    "func-call-latency/inferlib-r2r-resecho-callee",
    "func-call-latency/inferlib-r2r-resecho-callee-bindings",
    "func-call-latency/inferlib-r2r-resecho-caller",
    "func-call-latency/inferlib-p2r-echo-callee",
    "func-call-latency/inferlib-r2p-echo-caller",
    "func-call-latency/mono-r2r-echo-callee",
    "func-call-latency/mono-r2r-echo-caller",
    "snapshot-latency/snapshot-benchmark-bindings",
    "snapshot-latency/echo-caller",
    "benchdebug/inferlib-debug-r2p-echo-caller",
    "benchdebug/inferlib-debug-r2r-echo-callee-bindings",
]

[workspace.dependencies]
wit-bindgen = "0.48.0"
inferlet = { path = "../rust/inferlet" }
inferlet-macros = { path = "../rust/inferlet-macros" }

[profile.release]
lto = true
