[package]
name = "knowledge-graph"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlib-inference-bindings = { path = "../../rust/inferlib/inference-bindings" }
inferlib-run-bindings = { path = "../../rust/inferlib/run-bindings" }
inferlib-macros = { path = "../../rust/inferlib-macros" }
petgraph = { version = "0.8", default-features = false, features = ["graphmap", "stable_graph"] }
futures = "0.3"
wstd = "0.5.6"
