# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_runtime

@dataclass
class ToolCall:
    name: str
    arguments: str

class ChatFormatter:
    
    def add_assistant(self, content: str) -> None:
        result = componentize_py_runtime.call_import(3, [self, content])
        return
    def add_assistant_response(self, content: str, reasoning: Optional[str], tool_calls: Optional[List[ToolCall]]) -> None:
        result = componentize_py_runtime.call_import(4, [self, content, reasoning, tool_calls])
        return
    def add_system(self, content: str) -> None:
        result = componentize_py_runtime.call_import(5, [self, content])
        return
    def add_tool(self, content: str) -> None:
        result = componentize_py_runtime.call_import(6, [self, content])
        return
    def add_user(self, content: str) -> None:
        result = componentize_py_runtime.call_import(7, [self, content])
        return
    def clear(self) -> None:
        result = componentize_py_runtime.call_import(8, [self])
        return
    def has_messages(self) -> bool:
        result = componentize_py_runtime.call_import(9, [self])
        return result
    def __init__(self, template: str) -> None:
        tmp = componentize_py_runtime.call_import(10, [template])
        (_, func, args, _) = tmp.finalizer.detach()
        self.handle = tmp.handle
        self.finalizer = weakref.finalize(self, func, args[0], args[1])

    def render(self, add_generation_prompt: bool, begin_of_sequence: bool) -> str:
        result = componentize_py_runtime.call_import(11, [self, add_generation_prompt, begin_of_sequence])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])



