# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import models
from ..imports import poll
from ..imports import queues
import componentize_py_runtime


@dataclass
class SamplerConfig_Greedy:
    pass


@dataclass
class SamplerConfig_Multinomial:
    value: float


@dataclass
class SamplerConfig_TopP:
    value: Tuple[float, float]


@dataclass
class SamplerConfig_TopK:
    value: Tuple[float, int]


@dataclass
class SamplerConfig_MinP:
    value: Tuple[float, float]


@dataclass
class SamplerConfig_TopKTopP:
    value: Tuple[float, int, float]


SamplerConfig = Union[SamplerConfig_Greedy, SamplerConfig_Multinomial, SamplerConfig_TopP, SamplerConfig_TopK, SamplerConfig_MinP, SamplerConfig_TopKTopP]


class DecodeStepFuture:
    
    def get(self) -> Optional[int]:
        result = componentize_py_runtime.call_import(106, [self])
        return result
    def pollable(self) -> poll.Pollable:
        result = componentize_py_runtime.call_import(107, [self])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])


class FlushFuture:
    
    def is_ready(self) -> bool:
        result = componentize_py_runtime.call_import(108, [self])
        return result
    def pollable(self) -> poll.Pollable:
        result = componentize_py_runtime.call_import(109, [self])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])


@dataclass
class StopConfig:
    max_tokens: int
    eos_sequences: List[List[int]]

class GenerateFuture:
    
    def get(self) -> Optional[str]:
        result = componentize_py_runtime.call_import(110, [self])
        return result
    def pollable(self) -> poll.Pollable:
        result = componentize_py_runtime.call_import(111, [self])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])


class Context:
    
    def decode_step(self, sampler: SamplerConfig) -> int:
        result = componentize_py_runtime.call_import(74, [self, sampler])
        return result
    def decode_step_async(self, sampler: SamplerConfig) -> DecodeStepFuture:
        result = componentize_py_runtime.call_import(75, [self, sampler])
        return result
    def decode_step_dist(self, temperature: float, top_k: Optional[int]) -> queues.Distribution:
        result = componentize_py_runtime.call_import(76, [self, temperature, top_k])
        return result
    def detokenize(self, token_ids: List[int]) -> str:
        result = componentize_py_runtime.call_import(77, [self, token_ids])
        return result
    def drop_masked_kv_pages(self) -> None:
        result = componentize_py_runtime.call_import(78, [self])
        return
    def fill(self, text: str) -> None:
        result = componentize_py_runtime.call_import(79, [self, text])
        return
    def fill_assistant(self, text: str) -> None:
        result = componentize_py_runtime.call_import(80, [self, text])
        return
    def fill_system(self, text: str) -> None:
        result = componentize_py_runtime.call_import(81, [self, text])
        return
    def fill_token(self, new_token_id: int) -> None:
        result = componentize_py_runtime.call_import(82, [self, new_token_id])
        return
    def fill_tokens(self, new_token_ids: List[int]) -> None:
        result = componentize_py_runtime.call_import(83, [self, new_token_ids])
        return
    def fill_user(self, text: str) -> None:
        result = componentize_py_runtime.call_import(84, [self, text])
        return
    def fill_user_only(self, text: str) -> None:
        result = componentize_py_runtime.call_import(85, [self, text])
        return
    def flush(self) -> None:
        result = componentize_py_runtime.call_import(86, [self])
        return
    def flush_async(self) -> Optional[FlushFuture]:
        result = componentize_py_runtime.call_import(87, [self])
        return result
    def flush_chat_messages(self, add_generation_prompt: bool) -> None:
        result = componentize_py_runtime.call_import(88, [self, add_generation_prompt])
        return
    def fork(self) -> Self:
        result = componentize_py_runtime.call_import(89, [self])
        return result
    @classmethod
    def from_imported_state(cls, wit_model: models.Model, kv_page_ptrs: List[int], prefix_tokens: List[int], kv_page_last_len: int) -> Self:
        result = componentize_py_runtime.call_import(90, [wit_model, kv_page_ptrs, prefix_tokens, kv_page_last_len])
        return result
    def generate(self, sampler: SamplerConfig, stop_config: StopConfig) -> str:
        result = componentize_py_runtime.call_import(91, [self, sampler, stop_config])
        return result
    def generate_async(self, sampler: SamplerConfig, stop_config: StopConfig) -> GenerateFuture:
        result = componentize_py_runtime.call_import(92, [self, sampler, stop_config])
        return result
    def generate_with_beam(self, stop_config: StopConfig, beam_size: int) -> str:
        result = componentize_py_runtime.call_import(93, [self, stop_config, beam_size])
        return result
    def get_kv_page_last_len(self) -> int:
        result = componentize_py_runtime.call_import(94, [self])
        return result
    def get_kv_page_ptrs(self) -> List[int]:
        result = componentize_py_runtime.call_import(95, [self])
        return result
    def get_text(self) -> str:
        result = componentize_py_runtime.call_import(96, [self])
        return result
    def get_token_ids(self) -> List[int]:
        result = componentize_py_runtime.call_import(97, [self])
        return result
    def mask_token(self, index: int, mask: bool) -> None:
        result = componentize_py_runtime.call_import(98, [self, index, mask])
        return
    def mask_token_range(self, start: int, end: int, mask: bool) -> None:
        result = componentize_py_runtime.call_import(99, [self, start, end, mask])
        return
    def mask_tokens(self, indices: List[int], mask: bool) -> None:
        result = componentize_py_runtime.call_import(100, [self, indices, mask])
        return
    def __init__(self, wit_model: models.Model) -> None:
        tmp = componentize_py_runtime.call_import(101, [wit_model])
        (_, func, args, _) = tmp.finalizer.detach()
        self.handle = tmp.handle
        self.finalizer = weakref.finalize(self, func, args[0], args[1])

    def remove_adapter(self) -> None:
        result = componentize_py_runtime.call_import(102, [self])
        return
    def set_adapter(self, adapter_ptr: int) -> None:
        result = componentize_py_runtime.call_import(103, [self, adapter_ptr])
        return
    def set_adapter_random_seed(self, seed: int) -> None:
        result = componentize_py_runtime.call_import(104, [self, seed])
        return
    def verify_draft(self, draft_tokens: List[int], draft_pos_ids: List[int]) -> List[int]:
        result = componentize_py_runtime.call_import(105, [self, draft_tokens, draft_pos_ids])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])



