# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_runtime


def store_delete(key: str) -> None:
    result = componentize_py_runtime.call_import(112, [key])
    return
def store_exists(key: str) -> bool:
    result = componentize_py_runtime.call_import(113, [key])
    return result
def store_get(key: str) -> Optional[str]:
    result = componentize_py_runtime.call_import(114, [key])
    return result
def store_list_keys() -> List[str]:
    result = componentize_py_runtime.call_import(115, [])
    return result
def store_set(key: str, value: str) -> None:
    result = componentize_py_runtime.call_import(116, [key, value])
    return
