# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_runtime


def broadcast(topic: str, message: str) -> None:
    result = componentize_py_runtime.call_import(117, [topic, message])
    return
def receive() -> str:
    result = componentize_py_runtime.call_import(118, [])
    return result
def receive_blob() -> bytes:
    result = componentize_py_runtime.call_import(119, [])
    return result
def send(message: str) -> None:
    result = componentize_py_runtime.call_import(120, [message])
    return
def send_blob(data: bytes) -> None:
    result = componentize_py_runtime.call_import(121, [data])
    return
def subscribe(topic: str) -> str:
    result = componentize_py_runtime.call_import(122, [topic])
    return result
