# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_runtime

class Tokenizer:
    
    def detokenize(self, tokens: List[int]) -> str:
        result = componentize_py_runtime.call_import(24, [self, tokens])
        return result
    def get_special_tokens(self) -> Tuple[List[int], List[bytes]]:
        result = componentize_py_runtime.call_import(25, [self])
        return result
    def get_split_regex(self) -> str:
        result = componentize_py_runtime.call_import(26, [self])
        return result
    def get_vocabs(self) -> Tuple[List[int], List[bytes]]:
        result = componentize_py_runtime.call_import(27, [self])
        return result
    def tokenize(self, text: str) -> List[int]:
        result = componentize_py_runtime.call_import(28, [self, text])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])


class Model:
    
    def eos_tokens(self) -> List[List[int]]:
        result = componentize_py_runtime.call_import(12, [self])
        return result
    @classmethod
    def get_all_names(cls) -> List[str]:
        result = componentize_py_runtime.call_import(13, [])
        return result
    @classmethod
    def get_auto(cls) -> Self:
        result = componentize_py_runtime.call_import(14, [])
        return result
    @classmethod
    def get_by_name(cls, name: str) -> Optional[Self]:
        result = componentize_py_runtime.call_import(15, [name])
        return result
    def get_description(self) -> str:
        result = componentize_py_runtime.call_import(16, [self])
        return result
    def get_kv_page_size(self) -> int:
        result = componentize_py_runtime.call_import(17, [self])
        return result
    def get_name(self) -> str:
        result = componentize_py_runtime.call_import(18, [self])
        return result
    def get_prompt_template(self) -> str:
        result = componentize_py_runtime.call_import(19, [self])
        return result
    def get_service_id(self) -> int:
        result = componentize_py_runtime.call_import(20, [self])
        return result
    def get_tokenizer(self) -> Tokenizer:
        result = componentize_py_runtime.call_import(21, [self])
        return result
    def get_traits(self) -> List[str]:
        result = componentize_py_runtime.call_import(22, [self])
        return result
    def has_traits(self, required_traits: List[str]) -> bool:
        result = componentize_py_runtime.call_import(23, [self, required_traits])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])



