# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_runtime

@dataclass
class Distribution:
    ids: List[int]
    probs: List[float]

@dataclass
class ForwardPassResult:
    distributions: Optional[List[Distribution]]
    tokens: Optional[List[int]]

class ForwardPass:
    
    def attention_mask(self, mask: List[List[int]]) -> None:
        result = componentize_py_runtime.call_import(29, [self, mask])
        return
    def execute(self) -> ForwardPassResult:
        result = componentize_py_runtime.call_import(30, [self])
        return result
    def input_embed_ptrs(self, embed_ptrs: List[int], positions: List[int]) -> None:
        result = componentize_py_runtime.call_import(31, [self, embed_ptrs, positions])
        return
    def input_tokens(self, tokens: List[int], positions: List[int]) -> None:
        result = componentize_py_runtime.call_import(32, [self, tokens, positions])
        return
    def kv_cache(self, kv_page_ptrs: List[int], last_kv_page_len: int) -> None:
        result = componentize_py_runtime.call_import(33, [self, kv_page_ptrs, last_kv_page_len])
        return
    def output_distributions(self, indices: List[int], temperature: float, top_k: Optional[int]) -> None:
        result = componentize_py_runtime.call_import(34, [self, indices, temperature, top_k])
        return
    def output_embed_ptrs(self, embed_ptrs: List[int], indices: List[int]) -> None:
        result = componentize_py_runtime.call_import(35, [self, embed_ptrs, indices])
        return
    def output_tokens(self, indices: List[int], temperature: float) -> None:
        result = componentize_py_runtime.call_import(36, [self, indices, temperature])
        return
    def output_tokens_min_p(self, indices: List[int], temperature: float, min_p: float) -> None:
        result = componentize_py_runtime.call_import(37, [self, indices, temperature, min_p])
        return
    def output_tokens_top_k(self, indices: List[int], temperature: float, top_k: int) -> None:
        result = componentize_py_runtime.call_import(38, [self, indices, temperature, top_k])
        return
    def output_tokens_top_k_top_p(self, indices: List[int], temperature: float, top_k: int, top_p: float) -> None:
        result = componentize_py_runtime.call_import(39, [self, indices, temperature, top_k, top_p])
        return
    def output_tokens_top_p(self, indices: List[int], temperature: float, top_p: float) -> None:
        result = componentize_py_runtime.call_import(40, [self, indices, temperature, top_p])
        return
    def set_adapter(self, adapter_ptr: int) -> None:
        result = componentize_py_runtime.call_import(41, [self, adapter_ptr])
        return
    def set_adapter_seed(self, seed: int) -> None:
        result = componentize_py_runtime.call_import(42, [self, seed])
        return
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])


class KvPage:
    
    def ptr(self) -> int:
        result = componentize_py_runtime.call_import(43, [self])
        return result
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])


class Priority(Enum):
    LOW = 0
    NORMAL = 1
    HIGH = 2

class Queue:
    
    def allocate_adapter(self) -> int:
        result = componentize_py_runtime.call_import(44, [self])
        return result
    def allocate_embeds(self, count: int) -> List[int]:
        result = componentize_py_runtime.call_import(45, [self, count])
        return result
    def allocate_kv_pages(self, count: int) -> List[int]:
        result = componentize_py_runtime.call_import(46, [self, count])
        return result
    def calculate_embed_size(self, image_width: int, image_height: int) -> int:
        result = componentize_py_runtime.call_import(47, [self, image_width, image_height])
        return result
    def create_forward_pass(self) -> ForwardPass:
        result = componentize_py_runtime.call_import(48, [self])
        return result
    def deallocate_adapter(self, ptr: int) -> None:
        result = componentize_py_runtime.call_import(49, [self, ptr])
        return
    def deallocate_embeds(self, ptrs: List[int]) -> None:
        result = componentize_py_runtime.call_import(50, [self, ptrs])
        return
    def deallocate_kv_pages(self, ptrs: List[int]) -> None:
        result = componentize_py_runtime.call_import(51, [self, ptrs])
        return
    def debug_query(self, query: str) -> str:
        result = componentize_py_runtime.call_import(52, [self, query])
        return result
    def download_adapter(self, adapter_ptr: int, name: str) -> None:
        result = componentize_py_runtime.call_import(53, [self, adapter_ptr, name])
        return
    def embed_image(self, embed_ptrs: List[int], image_data: bytes, position_offset: int) -> None:
        result = componentize_py_runtime.call_import(54, [self, embed_ptrs, image_data, position_offset])
        return
    def export_adapter(self, ptr: int, name: str) -> None:
        result = componentize_py_runtime.call_import(55, [self, ptr, name])
        return
    def export_embeds(self, ptrs: List[int], name: str) -> None:
        result = componentize_py_runtime.call_import(56, [self, ptrs, name])
        return
    def export_kv_pages(self, ptrs: List[int], name: str) -> None:
        result = componentize_py_runtime.call_import(57, [self, ptrs, name])
        return
    @classmethod
    def from_model_name(cls, model_name: str) -> Self:
        result = componentize_py_runtime.call_import(58, [model_name])
        return result
    def get_all_exported_adapters(self) -> List[str]:
        result = componentize_py_runtime.call_import(59, [self])
        return result
    def get_all_exported_embeds(self) -> List[Tuple[str, int]]:
        result = componentize_py_runtime.call_import(60, [self])
        return result
    def get_all_exported_kv_pages(self) -> List[Tuple[str, int]]:
        result = componentize_py_runtime.call_import(61, [self])
        return result
    def get_service_id(self) -> int:
        result = componentize_py_runtime.call_import(62, [self])
        return result
    def import_adapter(self, name: str) -> int:
        result = componentize_py_runtime.call_import(63, [self, name])
        return result
    def import_embeds(self, name: str) -> List[int]:
        result = componentize_py_runtime.call_import(64, [self, name])
        return result
    def import_kv_pages(self, name: str) -> List[int]:
        result = componentize_py_runtime.call_import(65, [self, name])
        return result
    def initialize_adapter(self, adapter_ptr: int, rank: int, alpha: float, population_size: int, mu_fraction: float, initial_sigma: float) -> None:
        result = componentize_py_runtime.call_import(66, [self, adapter_ptr, rank, alpha, population_size, mu_fraction, initial_sigma])
        return
    def release_exported_adapter(self, name: str) -> None:
        result = componentize_py_runtime.call_import(67, [self, name])
        return
    def release_exported_embeds(self, name: str) -> None:
        result = componentize_py_runtime.call_import(68, [self, name])
        return
    def release_exported_kv_pages(self, name: str) -> None:
        result = componentize_py_runtime.call_import(69, [self, name])
        return
    def set_priority(self, priority: Priority) -> None:
        result = componentize_py_runtime.call_import(70, [self, priority])
        return
    def synchronize(self) -> bool:
        result = componentize_py_runtime.call_import(71, [self])
        return result
    def update_adapter(self, adapter_ptr: int, scores: List[float], seeds: List[int], max_sigma: float) -> None:
        result = componentize_py_runtime.call_import(72, [self, adapter_ptr, scores, seeds, max_sigma])
        return
    def upload_adapter(self, adapter_ptr: int, name: str, data: bytes) -> None:
        result = componentize_py_runtime.call_import(73, [self, adapter_ptr, name, data])
        return
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        (_, func, args, _) = self.finalizer.detach()
        self.handle = None
        func(args[0], args[1])


class ResourceType(Enum):
    KV_PAGE = 0
    EMBED = 1
    ADAPTER = 2


