# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_runtime


def debug_query(query: str) -> str:
    result = componentize_py_runtime.call_import(123, [query])
    return result
def get_all_models_with_traits(traits: List[str]) -> List[str]:
    result = componentize_py_runtime.call_import(124, [traits])
    return result
def get_arguments() -> List[str]:
    result = componentize_py_runtime.call_import(125, [])
    return result
def get_instance_id() -> str:
    result = componentize_py_runtime.call_import(126, [])
    return result
def get_version() -> str:
    result = componentize_py_runtime.call_import(127, [])
    return result
def set_return(value: str) -> None:
    result = componentize_py_runtime.call_import(128, [value])
    return
