[package]
name = "inferlib-inference"
version = "0.1.0"
authors = ["Pie Team"]

[runtime]
core = "^0.2.0"
mcp = "^0.2.0"

[wit]
exports = ["runtime", "messaging", "kvstore", "models", "queues", "formatter", "inference"]

[wit.with]
"wasi:io/poll@0.2.0" = "wasip2::io::poll"
