package pie:nbi;

world imports {
    import runtime;
    import messaging;
    import l4m;
    import l4m-vision;
    import ping;
}

world app {
    include imports;
    export run;
}

world server {
    include imports;
    export wasi:http/incoming-handler@0.2.4;
}