interface l4m-vision {
    use l4m.{model};

    embed-image: func(model:borrow<model>, stream-id:u32, embs:list<u32>, image-blob:list<u8>);
    //embed-video: func(stream-id:u32, embs:list<u32>, url:string);
}
