interface messaging {

    // Import pollable functionality from the WASI IO poll package
    use wasi:io/poll@0.2.4.{pollable};

    send: func(message: string);
    receive: func() -> receive-result;

    broadcast: func(topic:string, message: string);
    subscribe: func(topic:string) -> subscription;

    resource receive-result {
        pollable: func() -> pollable;
        get: func() -> option<string>; // None if not ready
    }

    resource subscription {
        pollable: func() -> pollable;
        get: func() -> option<string>;
        unsubscribe: func();
    }
}
