package inferlet:exec;

world imports {
    include inferlet:core/imports;
    include inferlet:image/imports;
    include inferlet:adapter/imports;
    include inferlet:zo/imports;
    include inferlet:actor/imports;
}

world exec {
    include inferlet:core/imports;
    include inferlet:image/imports;
    include inferlet:adapter/imports;
    include inferlet:zo/imports;
    include inferlet:actor/imports;
    export inferlet:core/run;
}